---
- name: Configure VyOS Hostname
  hosts: vyos
  gather_facts: no
  
  vars:
    new_hostname: "my-vyos-router"

  tasks:
  - name: Apply the provided configuration
    vyos.vyos.vyos_hostname:
      config:
        hostname: RubenRouter
      state: merged
