---
- name: Configure VyOS Hostname
  hosts: vyos
  gather_facts: no

  tasks:
  - name: show configuration on ethernet devices eth0
    vyos.vyos.vyos_command:
      commands:
      - show interfaces ethernet eth0
    register: interface
  
  - name: Debug
    debug:
      msg: "{{ interface }}"
