---
- name: Configure VyOS Hostname
  hosts: vyos
  gather_facts: no
  
  vars:
    new_hostname: "my-vyos-router"

  tasks:
    - name: Set new hostname
      vyos_command:
        commands: "set system host-name my-vyos-router"
      register: output

    - name: Commit changes
      vyos_command:
        commands: "commit"

    - name: Save configuration
      vyos_command:
        commands: "save"

    - name: Display output
      debug:
        var: output.stdout_lines
